service: fire-danger-rating # NOTE: update this with your service name

# Load environment variables from .env files (default: false)
# See https://www.serverless.com/framework/docs/environment-variables
useDotenv: true
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 60 # optional, in seconds, default is 6
  environment:
    featureServerUrl: ${env:featureServerUrl}
    clientId: ${env:clientId}
    clientSecret: ${env:clientSecret}
    fsTimeExtentUrl: ${env:fsTimeExtentUrl}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource:
            - '*'

functions:
  sync:
    handler: index.sync
    description: Sync XML Files from FTP into a National 4-day Fire Danger Rating Layer on ArcGIS Online
    timeout: 60 # optional, in seconds, default is 6
    events:
      - schedule:
          enabled: true
          rate: cron(0 1,4,7,20,21 * * ? *) # 7am, 8am, midday, 3pm, 6pm, Melbourne time
# plugins:
#   - serverless-offline
